### ISSUE TITLE
redirectUri defaults to `""`, overriding NEXT_PUBLIC_WORKOS_REDIRECT_URI

### ISSUE THREAD

**Issue by sestinj** [workos/authkit-nextjs#107]
Right now I have to do the following:

```ts
export default authkitMiddleware({
  middlewareAuth: {
    enabled: true,
    unauthenticatedPaths: [],
  },
  redirectUri: process.env.NEXT_PUBLIC_WORKOS_REDIRECT_URI,
});
```

because `redirectUri` is by default set to `""` right here: https://github.com/workos/authkit-nextjs/commit/845d4ae17be46b88ef423b365b8aa81e9103d09e#diff-0626369278c89781505d2c04865ecce1302e979271bcfb471e029c19addc13a0R8

This was causing me to get 500 errors from WorkOS because the user_management/authorization URL that was constructed in  `get-authorization-url.ts` didn't have a redirect URI.

**Comment by PaulAsjes** [comment]
Thanks for the report, will have a fix up soon.

**Comment by sestinj** [comment]
Thanks so much Paul!
