### ISSUE TITLE
Deploying to Vercel throw NoApiKeyProvideException

### ISSUE THREAD

**Issue by sheldonvaughn** [workos/authkit-nextjs#113]
Deploying to Vercel returning an issue:

```
app-name:build:    Collecting page data ...
app-name:build: NoApiKeyProvidedException: Missing API key. Pass it to the constructor or define it in the WORKOS_API_KEY environment variable.
app-name:build:     at new E (/vercel/path0/apps/app-name/.next/server/chunks/941.js:29:100117)
app-name:build:     at new h (/vercel/path0/apps/app-name/.next/server/chunks/941.js:29:39452)
app-name:build:     at 68791 (/vercel/path0/apps/app-name/.next/server/chunks/941.js:30:79751)
app-name:build:     at t (/vercel/path0/apps/app-name/.next/server/webpack-runtime.js:1:143)
app-name:build:     at 98387 (/vercel/path0/apps/app-name/.next/server/chunks/941.js:30:40890)
app-name:build:     at t (/vercel/path0/apps/app-name/.next/server/webpack-runtime.js:1:143)
app-name:build:     at 83024 (/vercel/path0/apps/app-name/.next/server/chunks/770.js:3:67080)
app-name:build:     at t (/vercel/path0/apps/app-name/.next/server/webpack-runtime.js:1:143)
app-name:build:     at 65843 (/vercel/path0/apps/app-name/.next/server/app/_not-found/page.js:1:5444)
app-name:build:     at t (/vercel/path0/apps/app-name/.next/server/webpack-runtime.js:1:143) {
app-name:build:   status: 500
app-name:build: }
app-name:build: 
app-name:build: > Build error occurred
app-name:build: Error: Failed to collect page data for /_not-found
app-name:build:     at /vercel/path0/node_modules/.pnpm/next@14.2.15_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/build/utils.js:1268:15
app-name:build:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
app-name:build:   type: 'Error'
app-name:build: }
app-name:build:  ELIFECYCLE  Command failed with exit code 1.
app-name:build: ERROR: command finished with error: command (/vercel/path0/apps/app-name) /pnpm9/node_modules/.bin/pnpm run build exited (1)
app-name#build: command (/vercel/path0/apps/app-name) /pnpm9/node_modules/.bin/pnpm run build exited (1)
```

.vercel/.env.development.local variables match

```
WORKOS_CLIENT_ID="client_..." # retrieved from the WorkOS dashboard
WORKOS_API_KEY="sk_test_..." # retrieved from the WorkOS dashboard
WORKOS_COOKIE_PASSWORD="<your password>" # generate a secure password here
```

**Comment by iohcidnal** [comment]
I am also getting the same error deploying in Vercel.

**Comment by sheldonvaughn** [comment]
Hey @iohcidnal - we were able to resolve this issue by ensuring the environment variables were populated as follows and that npm build or pnpm build are being used as the build command in Vercel:

![image](https://github.com/user-attachments/assets/765bdd12-7599-4665-a065-b304d6f88e76)

Hoping that helps resolve this for you but keep us posted!

**Comment by iohcidnal** [comment]
Thanks @sheldonvaughn! I already have my env vars declared this way in Vercel, but I still get the error. I am also using turbo repo.

**Comment by iohcidnal** [comment]
I think I figured out what's going on. Since I'm using turbo repo, the default build command was set to `turbo run build`, causing the error. Replacing the build command with `npm run build` seemed to work. The confusing part is running `turbo run build` locally worked but not in Vercel.

**Comment by sheldonvaughn** [comment]
Thanks @iohcidnal - I'll add that turbo repo and the turbo run build seem to be part of the issue here and close the issue. Hoping this helps with any future finders of this error - thanks for your detailed response!

**Comment by kittenkill** [comment]
Hi!

Is there a way to defer the definition WorkOS's env variable at runtime?

Currently, its forcing me to define the env's at build time, so when buildling a container, the env var is backed into it, with no option to change its values.

**Comment by frederikvanhevel** [comment]
> Hi!
> 
> Is there a way to defer the definition WorkOS's env variable at runtime?
> 
> Currently, its forcing me to define the env's at build time, so when buildling a container, the env var is backed into it, with no option to change its values.

Im not using vercel but im facing the same issue. During build nextjs executes the code which results in the error. You can see how auth0 fixed this issue: https://github.com/auth0/nextjs-auth0/issues/1356#issuecomment-1799283394

Please reopen this issue.
