### ISSUE TITLE
Cloudflare unable to verify I am a human (I am, I promise)

### ISSUE THREAD

**Issue by sestinj** [workos/authkit-nextjs#117]
**Describe the bug**
On occasion, login through AuthKit requires checking the Cloudflare box to verify that I am a human. Sometimes I check it once and proceed, but other times I repeatedly am confronted with the check box, which tells me it failed to verify I am a human.

<img width="465" alt="Screenshot 2024-10-21 at 1 13 22 PM" src="https://github.com/user-attachments/assets/73f7d680-0949-4ec6-baf8-2ab6306cdb2c">

I'm not certain this is the correct place to be asking this, as it seems likely that Cloudflare is just configured in front of auth.workos.com, but it seemed like a good place to start—if you can direct me to a better channel that would be extremely helpful!

Thank you : )

**Expected behavior**
Check the box once and proceed

**Desktop (please complete the following information):**
 - OS: MacOS 14.3
 - Browser: Arc
 - authkit-nextjs version: 0.12.2
 - Next.js version: 14.2.15

**Comment by PaulAsjes** [comment]
Hey there, this isn't a problem with authkit-nextjs specifially so I'm going to close this issue, but we're aware of issues with turnstile (Cloudflare's CAPTCHA solution). If you're continuing to see problems I recommend reaching out to WorkOS support (support@workos.com) so they can start a thread with you.
