### ISSUE TITLE
cannot access session info on server routes

### ISSUE THREAD

**Issue by sr0m** [workos/authkit-nextjs#131]
**Describe the bug**
I have a default middleware setup. a getSession works fine on client components, but it appears that the cookie is not available on calls from server routes. 

**middleware**

```
import { authkitMiddleware } from "@workos-inc/authkit-nextjs";
export default authkitMiddleware();
export const config = {
  matcher: ['/dashboard', '/employees', '/organization', '/time'],
}
```

session lookup:
```

export async function GET(request: Request) {

  const session = await getSession();
    console.log("session:", session);
  }
  
```
calls from a client component work correctly: It appears that a call from a server route does not have access to the wos_session cookie? (prints { user: null } )

**Comment by PaulAsjes** [comment]
Hey there, I'm unable to recreate this locally. Which route are you hitting that evokes the session lookup?

**Comment by sr0m** [comment]
I am closing this - after resetting the project and wiping all the caches, I am unable to recreate it.
