### ISSUE TITLE
Allow wildcard paths in the redirect URL 

### ISSUE THREAD

**Issue by mattbf** [workos/authkit-nextjs#144]
**Describe the bug**
Setting static redirect URLs in the workOS dashboard means that our apps can **only** redirect to these exact urls after logging in (otherwise there is an 'incorrecet redirect url' error). 
![image](https://github.com/user-attachments/assets/be399d5d-f5c9-4319-9743-99bd15d1214e)

If a user is on `example.com/some/path` → goes to the login page → should be able to be redirected back to where they started, instead of always being redirected to the static login page `example.com/`

**Expected behavior**
What would be nice is if we could define a redirect domain or just redirect url with wildcard path, something like:
`example.com/*`
Then, in the API, our redirect URL can be handled by something like this:
```ts
// get the path the user was on
 const redirectPath = encodeURIComponent(
      (req.query.redirectPath as string) || "/",
    );

// response to Authkit, getting a redirect url from workOS API
  res.status(401).json({
      ok: false,
      redirectUrl: workos.userManagement.getAuthorizationUrl({
        provider: "authkit",
        redirectUri: `${BACKEND_URL}/api/v1/auth/callback?redirectPath=${redirectPath}`,
        clientId,
      }),
    });

 // in the /callback endpoint
 res.redirect(`${FRONTEND_URL}${redirectPath}`);

```

**Comment by PaulAsjes** [comment]
The callback URI needs to be static, to help solve this use case you can [pass in](https://github.com/workos/authkit-nextjs/blob/main/src/get-authorization-url.ts#L14) `state` in `workos.userManagement.getAuthorizationURL`. After being redirected to the callback URL you can extract the intended path from `state` and redirect the user. Which is exactly what we do in the [callback method](https://github.com/workos/authkit-nextjs/blob/main/src/authkit-callback-route.ts#L24). 

This should already be handled by the authkit-nextjs library, are you seeing different behaviour?

**Comment by mattbf** [comment]
I see, I guess this is because I'm using custom nextjs middleware and the workos nodejs package to handle auth (waiting for [Authkit custom middleware](https://github.com/workos/authkit-nextjs/issues/47)).

I think I can implement this myself though by passing in that state. Thanks @PaulAsjes!
