### ISSUE TITLE
Improve Signup Process Efficiency in Authkit

### ISSUE THREAD

**Issue by gorbulls456667** [workos/authkit-nextjs#22]
The signup process, involving email and password entry, appears overly cumbersome compared to contemporary standards. Following signup completion, Authkit requires users to re-enter the same credentials for logging in before requesting an OTP.

Upon initial email and password submission during signup, the system should immediately prompt for OTP without requiring an additional login step.

### In general, the preferred behavior is as follows:

**For the conventional method (other Auth providers follow this approach):**
- I sign up by entering my email and password.
- The OTP code is requested and sent via email, which I then enter.
- I am automatically logged in.

**However, with Authkit:**
- I sign up by entering my email and password.
- Successful signup completion is confirmed.
- I am prompted to log in with my email and password.
- Once logged in, the OTP code is requested and sent via email, which I enter.
- Now, I am logged in.

**Comment by PaulAsjes** [comment]
Thanks for the feedback! We're currently evaluating ways to make this process more streamlined.

**Comment by k11kirky** [comment]
+1 this would be great, I have also had customers inform me that they had to verify they are human multiple times throughout the flow.

**Comment by MikeCarbone** [comment]
@k11kirky I ran into this issue today in authkit as well. I had to go through the cloudflare verification process multiple times throughout the sign up flow. I was prompted after every single step in the process (and successfully validated I was human each time of course)

**Comment by PaulAsjes** [comment]
Hi all, we've heard your feedback and streamlined the sign up/sign in process: https://workos.com/changelog/sign-in-on-signup

I'm going to close this issue as it's not really an issue with the authkit-nextjs library, but feel free to open up another issue if you have a problem with the library specifically.
