### ISSUE TITLE
Callback after signup?

### ISSUE THREAD

**Issue by ChristoRibeiro** [workos/authkit-nextjs#30]
Hi, 

Is there a callback when a user has successfully signed up?

I would like to make a database call just after a signup.

Thanks for your help.

**Comment by PaulAsjes** [comment]
The most reliable way to write to your database after a successful signup would be via [webhooks](https://workos.com/docs/events/data-syncing/webhooks). It's unsafe to rely on a callback as the user might close the tab or window before the redirect to your site is complete. 

Safest way is to listen for the `user.created` [webhook](https://workos.com/docs/events) and perform your database writes accordingly.
