### ISSUE TITLE
No `getSignUpUrl` import?

### ISSUE THREAD

**Issue by ChristoRibeiro** [workos/authkit-nextjs#31]
Hi, 

The doc mentions `getSignInUrl` and `getSignUpUrl`, but it seems that `getSignUpUrl` is not available to import. 

Is it normal?

**Comment by PaulAsjes** [comment]
This has just been released, install version v.0.5.0 and you should see `getSignUpUrl`.

**Comment by ChristoRibeiro** [comment]
I got the `v0.5.0` and it seems the module is broken:

```Cannot find module '@workos-inc/authkit-nextjs' or its corresponding type declarations.```

**Comment by PaulAsjes** [comment]
Sorry about that, our new github action was missing a step. Version `v0.5.1` should work correctly.

**Comment by PaulAsjes** [comment]
You most likely don't have `WORKOS_REDIRECT_URI` set in your environment variables. See the readme for further instructions.
