### ISSUE TITLE
Why on apps Redirects section logout is lost

### ISSUE THREAD

**Issue by taroom** [workos/authkit-nextjs#52]
I'm using nextjs, when im going to logout then show error "Something Went Wrong" and on url https://error.workos.com/user_management/app-homepage-url-not-found. then i searching for that section and for app homepage url is gone. where i can set homepage url in sign out action
![image](https://github.com/workos/authkit-nextjs/assets/5124127/0ac75dca-d869-4e18-b528-023700def6e4)

**Comment by PaulAsjes** [comment]
You'd set your homepage URL in your WorkOS dashboard: 

![CleanShot 2024-06-26 at 16 35 02](https://github.com/workos/authkit-nextjs/assets/108872335/a6879cde-a83f-40db-a54f-9aee17b402dc)

**Comment by taroom** [comment]
thats display is not exist on redirects

**Comment by PaulAsjes** [comment]
You'll need to enable User Management first. You can do so by navigating to the "Users" page in the WorkOS dashboard and following the steps there. Once that's set up you'll be able to set an app homepage.
