### ISSUE TITLE
Property 'accessToken' does not exist on type 'UserInfo | NoUserInfo'.ts(2339)

### ISSUE THREAD

**Issue by vinson14** [workos/authkit-nextjs#54]
`const { accessToken } = await getUser();`

Attempted to retrieve the accessToken according to the example given in the documentation but it is resulting in a Typescript error.

`Property 'accessToken' does not exist on type 'UserInfo | NoUserInfo'.ts(2339)`

**Comment by PaulAsjes** [comment]
Hi there, which version of the library are you using?

**Comment by vinson14** [comment]
I’m using 0.6.1

**Comment by vinson14** [comment]
I noticed that in the library, accessToken is missing under NoUserInfo interface

**Comment by PaulAsjes** [comment]
I see the issue, it's missing from the interface as you mentioned: https://github.com/workos/authkit-nextjs/blob/main/src/interfaces.ts#L26-L32

I'll get a fix up soon.

**Comment by vinson14** [comment]
Thanks for the help
